// examples/with-svelte/src/Dash.svelte
<script lang="ts">
  import type { PlaybackState } from "@headlessplayback/core"
  import { dashPlaybackPlugin } from "@headlessplayback/dash-plugin"
  import { usePlayback } from "@headlessplayback/svelte"
  import { onDestroy, onMount } from "svelte"

  usePlayback.use(dashPlaybackPlugin)

  const source1 = "https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd"
  const source2 =
    "https://rdmedia.bbc.co.uk/elephants_dream/1/client_manifest-all.mpd"

  const id = "dash"
  const {
    activate,
    playbackActions,
    playbackState: _playbackState,
  } = usePlayback({
    id,
  })

  let source = source1
  let playbackState: PlaybackState

  const unsubscribe = _playbackState.subscribe((value: PlaybackState) => {
    playbackState = value
  })

  onMount(() => {
    activate()
  })

  onDestroy(() => {
    unsubscribe()
  })

  const handleSource = async (source: string) => {
    playbackActions.loadDashSource({
      source,
    })
  }

  $: handleSource(source)

  const jumpTo = (time: number) => {
    playbackActions.setCurrentTime(time)
  }
</script>

<div class="border-fuchsia border-1 h-[400px] w-[600px]">
  <video class="h-full w-full" {id} controls> <track kind="captions" /></video>
</div>

<p>Current time: {playbackState.currentTime}</p>

<p>Duration: {playbackState.duration}</p>

<strong
  >BitrateInfo: {playbackState.bitrateInfo
    .map((level) => level.height)
    .join(", ")}</strong
>

<div class="flex flex-col items-start space-y-1">
  <button
    on:click={() => {
      if (source === source1) {
        source = source2
      } else {
        source = source1
      }
    }}>Switch stream</button
  >

  <button
    class="rounded-md bg-violet-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600"
    on:click={() => jumpTo(playbackState.currentTime + 5)}>Next 5s</button
  >
  <button
    class="rounded-md bg-violet-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600"
    on:click={() => jumpTo(playbackState.currentTime - 5)}>Prev 5s</button
  >
</div>

// examples/with-angular/src/app/dash.component.ts
import { AfterViewInit, Component } from "@angular/core"
import { PlaybackService, PlaybackState } from "@headlessplayback/angular"
import { dashPlaybackPlugin } from "@headlessplayback/dash-plugin"
import { sleep } from "./helper"
PlaybackService.use(dashPlaybackPlugin)

const source1 = "https://dash.akamaized.net/akamai/bbb_30fps/bbb_30fps.mpd"
const source2 =
  "https://rdmedia.bbc.co.uk/elephants_dream/1/client_manifest-all.mpd"

@Component({
  selector: "playback-dash",
  templateUrl: "./dash.component.html",
  providers: [PlaybackService],
})
export class PlaybackDashComponent implements AfterViewInit {
  id = "dash"
  source = source1
  playbackState: PlaybackState

  constructor(private playbackService: PlaybackService) {
    this.playbackService.usePlayback({ id: this.id })
    this.playbackState = this.playbackService.playbackState
  }

  async ngAfterViewInit() {
    await sleep(0)
    this.playbackService.activate()
    this.playbackService.playbackState$.subscribe((state) => {
      this.playbackState = state
    })
    this.playbackService.playbackActions.loadDashSource({
      source: this.source,
    })
  }

  switchStream() {
    this.source = this.source === source1 ? source2 : source1
    this.playbackService.playbackActions.loadDashSource({
      source: this.source,
    })
  }

  jumpTo(time: number) {
    this.playbackService.playbackActions.setCurrentTime(time)
  }

  getBitrateInfo() {
    return this.playbackState.bitrateInfo
      .map((level) => level.height)
      .join(", ")
  }
}

<div class="border-fuchsia border-1 h-[400px] w-[600px]">
  <video [id]="id" class="h-full w-full" controls>
    <track kind="captions" />
  </video>
</div>

<p>Current time: {{ playbackState.currentTime }}</p>

<p>Duration: {{ playbackState.duration }}</p>
<strong>BitrateInfo: {{ getBitrateInfo() }}</strong>

<div class="flex flex-col items-start space-y-1">
  <button
    class="rounded-md bg-violet-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600"
    (click)="switchStream()"
  >
    Switch stream
  </button>

  <button
    class="rounded-md bg-violet-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600"
    (click)="jumpTo(playbackState.currentTime + 5)"
  >
    Next 5s
  </button>
  <button
    class="rounded-md bg-violet-600 px-2.5 py-1.5 text-sm font-semibold text-white shadow-sm hover:bg-violet-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-violet-600"
    (click)="jumpTo(playbackState.currentTime - 5)"
  >
    Prev 5s
  </button>
</div>
