// examples/with-vue/src/App.vue
<script lang="ts" setup>
import { usePlayback } from "@headlessplayback/vue"
import { hlsPlaybackPlugin } from "@headlessplayback/plugins"
import { onMounted, ref, watch } from "vue"
usePlayback.use(hlsPlaybackPlugin)

let id = "video"

const { activate, playbackActions, playbackState } = usePlayback({
  id,
})

const source1 = "https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8"
const source2 = "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8"
const showDuration = ref(true)
const source = ref(source1)

onMounted(() => {
  activate()
})

watch(
  source,
  () => {
    playbackActions.load({
      id,
      source: source.value,
    })
  },
  { immediate: true, flush: "sync" },
)

// const handleSource = async (source: string) => {
//   playbackActions.load({
//     id: "video",
//     source,
//   })
// }

const jumpTo = (time: number) => {
  playbackActions.setCurrentTime(time)
}
</script>

<template>
  <div id="app" class="p-4">
    <div class="border-emerald border-1 h-[400px] w-[600px]">
      <video :id="id" class="h-full w-full" controls>
        <track kind="captions" />
      </video>
    </div>

    <p>Current time: {{ playbackState.currentTime }}</p>

    <p v-if="showDuration">Duration: {{ playbackState.duration }}</p>

    <div class="flex flex-col items-start">
      <button @click="source = source === source1 ? source2 : source1">Switch stream</button>

      <button @click="jumpTo(playbackState.currentTime + 5)">Next 5s</button>
      <button @click="jumpTo(playbackState.currentTime - 5)">Prev 5s</button>
      <button @click="showDuration = !showDuration">Toggle show duration</button>
    </div>
  </div>
</template>

// examples/with-svelte/src/App.svelte
<script lang="ts">
  import { usePlayback } from "@headlessplayback/svelte"
  import { hlsPlaybackPlugin } from "@headlessplayback/plugins"
  import type { PlaybackState } from "@headlessplayback/core"
  import { onDestroy, onMount, tick } from "svelte"
  usePlayback.use(hlsPlaybackPlugin)

  const {
    activate,
    playbackActions,
    playbackState: _playbackState,
  } = usePlayback({
    id: "video",
  })

  const source1 = "https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8"
  const source2 = "https://cdn.jwplayer.com/manifests/pZxWPRg4.m3u8"

  let id = "video"
  let source = source1
  let showDuration = true

  let playbackState: PlaybackState

  const unsubscribe = _playbackState.subscribe((value: PlaybackState) => {
    playbackState = value
  })

  onMount(() => {
    activate()
  })

  onDestroy(() => {
    unsubscribe()
  })

  const handleSource = async (source: string) => {
    playbackActions.load({
      source,
    })
  }

  $: handleSource(source)
</script>

<div id="app" class="p-4">
  <div class="border-emerald border-1 h-[400px] w-[600px]">
    <!-- src={source} -->
    <video {id} class="h-full w-full" controls>
      <track kind="captions" />
    </video>
  </div>

  <p>Current time: {playbackState.currentTime}</p>
  {#if showDuration}
    <p>Duration: {playbackState.duration}</p>
  {/if}

  <div class="flex flex-col items-start">
    <button
      on:click={() => {
        if (source === source1) {
          source = source2
        } else {
          source = source1
        }
      }}>Switch stream</button
    >

    <button
      on:click={() => {
        playbackActions.setCurrentTime(playbackState.currentTime + 5)
      }}>Next 5s</button
    >
    <button
      on:click={() => {
        playbackActions.setCurrentTime(playbackState.currentTime - 5)
      }}>Prev 5s</button
    >
    <button
      on:click={() => {
        showDuration = !showDuration
      }}
    >
      Toggle show duration
    </button>
  </div>
</div>
